apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-emulator
spec:
  selector:
    matchLabels: { app: emulator }
  template:
    metadata:
      labels: { app: emulator }
    spec:
      containers:
      - name: emulator
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
        command: ["gcloud", "beta", "emulators", "pubsub", "start", "--project=local-project", "--host-port=0.0.0.0:8085"]
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-emulator
spec:
  selector: { app: emulator }
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085