global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: [ 'host.docker.internal:9090' ]

  - job_name: redis_exporter
    static_configs:
      - targets: [ 'redis_exporter:9121' ]

  - job_name: 'Spring Boot Cache Redis'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'spring-boot-cache-redis'
