version: "3.9"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass replaceme
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
