services:
  frontend:
    image: web
    build:
      context: .
      target: web
      tags:
        - web:latest
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - front-tier
      - back-tier

  backend:
    image: pact
    build:
      context: .
      target: pact
      tags:
        - pact:latest
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    volumes:
      - ./pacts:/app/pacts
    networks:
      - back-tier

networks:
  front-tier: {}
  back-tier: {}
