apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-gin
  labels:
    app: consumer-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-gin
  template:
    metadata:
      labels:
        app: consumer-gin
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "consumer-gin"
        dapr.io/app-port: "8080"
        dapr.io/config: "appconfig"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: consumer-gin
          image: agnostic-consumer-gin:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DAPR_PUBSUB_NAME
              value: order-pubsub
            - name: DAPR_TOPIC_NAME
              value: orders
            - name: DAPR_SUBSCRIPTION_ROUTE
              value: /orders
            - name: OTEL_SERVICE_NAME
              value: consumer-gin
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.$(POD_NAMESPACE).svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=local,service.namespace=agnostic
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-gin
  labels:
    app: consumer-gin
spec:
  selector:
    app: consumer-gin
  ports:
    - name: http
      port: 8080
      targetPort: http
