apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-ktor
  labels:
    app: consumer-ktor
    app.kubernetes.io/name: consumer-ktor
    app.kubernetes.io/component: consumer
    agnostic.io/stack: ktor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-ktor
  template:
    metadata:
      labels:
        app: consumer-ktor
        app.kubernetes.io/name: consumer-ktor
        app.kubernetes.io/component: consumer
        agnostic.io/stack: ktor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "consumer-ktor"
        dapr.io/app-port: "8080"
        dapr.io/config: "appconfig"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: consumer-ktor
          image: agnostic-consumer-ktor:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_SERVICE
              value: consumer-ktor
            - name: APP_ROLE
              value: consumer
            - name: APP_STACK
              value: ktor
            - name: APP_VERSION
              value: "1.0.0"
            - name: DEPLOYMENT_ENV
              value: local
            - name: DAPR_PUBSUB_NAME
              value: order-pubsub
            - name: DAPR_TOPIC_NAME
              value: orders
            - name: DAPR_SUBSCRIPTION_ROUTE
              value: /orders
            - name: OTEL_SERVICE_NAME
              value: consumer-ktor
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.$(POD_NAMESPACE).svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=$(DEPLOYMENT_ENV),service.namespace=agnostic,service.name=$(APP_SERVICE),service.version=$(APP_VERSION),service.role=$(APP_ROLE),service.stack=$(APP_STACK),k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.node.name=$(NODE_NAME)
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-ktor
  labels:
    app: consumer-ktor
spec:
  selector:
    app: consumer-ktor
  ports:
    - name: http
      port: 8080
      targetPort: http
