apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-gin
  labels:
    app: producer-gin
    app.kubernetes.io/name: producer-gin
    app.kubernetes.io/component: producer
    agnostic.io/stack: gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-gin
  template:
    metadata:
      labels:
        app: producer-gin
        app.kubernetes.io/name: producer-gin
        app.kubernetes.io/component: producer
        agnostic.io/stack: gin
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "producer-gin"
        dapr.io/app-port: "8080"
        dapr.io/config: "appconfig"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: producer-gin
          image: agnostic-producer-gin:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_SERVICE
              value: producer-gin
            - name: APP_ROLE
              value: producer
            - name: APP_STACK
              value: gin
            - name: APP_VERSION
              value: "1.0.0"
            - name: DEPLOYMENT_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/environment']
            - name: DAPR_PUBSUB_NAME
              value: order-pubsub
            - name: DAPR_TOPIC_NAME
              value: orders
            - name: OTEL_SERVICE_NAME
              value: producer-gin
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.$(POD_NAMESPACE).svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=$(DEPLOYMENT_ENV),service.namespace=agnostic,service.name=$(APP_SERVICE),service.version=$(APP_VERSION),service.role=$(APP_ROLE),service.stack=$(APP_STACK),k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.node.name=$(NODE_NAME)
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: producer-gin
  labels:
    app: producer-gin
spec:
  selector:
    app: producer-gin
  ports:
    - name: http
      port: 8080
      targetPort: http
