# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  spring-boot-cache-redis-build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-boot-cache-redis

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    - name: Start Docker Compose
      run: |
        docker compose -f docker/docker-compose.yml up -d
        docker ps
        echo "curl -v http://localhost:9121/health"
        curl -v http://localhost:9121/health
        echo "curl -v http://localhost:9090/-/healthy"
        curl -v http://localhost:9090/-/healthy
        echo "curl -v --retry-connrefused --retry-max-time 30 --retry 10 http://localhost:3000/api/health"
        curl -v --retry-connrefused --retry-max-time 30 --retry 10 http://localhost:3000/api/health
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: spring-boot-cache-redis
    - name: Execute Gradle build
      run: ./gradlew build --full-stacktrace
    - name: Stop Docker Compose
      if: ${{ always() }}
      run: docker compose -f docker/docker-compose.yml down
