# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: vue-pact-playwright CI

on:
  push:
    paths:
      - "vue-pact-playwright/**"
    branches: [ "master" ]
  pull_request:
    paths:
      - "vue-pact-playwright/**"
    branches: [ "*" ]
env:
  working-directory: vue-pact-playwright
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    env:
      CI: true
      GITHUB_ACTIONS: true
    strategy:
      matrix:
        node-version: [22.15]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: vue-pact-playwright/pnpm-lock.yaml
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Build app
      run: pnpm build
    - name: Run Unit Tests
      run: pnpm test:unit --coverage

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: coverage
        path: ${{ env.working-directory }}/coverage/
        if-no-files-found: error
        retention-days: 30
    - name: Run Integration Tests
      run: pnpm test:integration
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run E2E Tests
      run: pnpm test:e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ${{ env.working-directory }}/playwright-report/
        if-no-files-found: error
        retention-days: 30
